let dato= "Descripción";
let entero= 16;
let flotante= 17.5;
let verdadero= true;
let falso= false;
let nulo= null;
let indefinido= undefined
console.log(dato);
console.log(typeof(dato));
console.log(entero);
console.log(typeof(entero));
console.log(flotante);
console.log(typeof(flotante));
console.log(verdadero);
console.log(typeof(verdadero));
console.log(falso);
console.log(typeof(falso));
console.log(nulo);
console.log(typeof(nulo));
console.log(indefinido);
console.log(typeof(indefinido));
